
export enum DeviceType {
  Auto = "✨ AI Auto-Detect (Best Match for Image)",
  Smartphone = "Modern Flagship Smartphone (iPhone 15 Pro Max style), Titanium Frame, Slim Bezels",
  MarketingHero = "Generic Premium Smartphone, No Logo, Front-Facing, Floating Presentation",
  Tablet = "12.9-inch Pro Tablet, Aluminum Unibody, Edge-to-Edge Liquid Retina Display",
  Laptop = "Premium 16-inch Laptop, Silver Aluminum Body, Modern Trackpad, Open 90 Degrees",
  Desktop = "27-inch 5K Monitor on Aluminum Stand, Minimalist Desk Setup, Clean Cable Management",
  SmartWatch = "Ultra-Modern Smart Watch, 49mm Titanium Case, Vivid Always-On Display"
}

export enum BackgroundStyle {
  Auto = "✨ AI Auto-Select (Complimentary Vibe)",
  Custom = "✨ Custom Text Prompt (AI Generated)",
  Studio = "Solid Color Infinite Backdrop, Professional Product Studio, Minimalist",
  Office = "Blurred Executive Office Background, Glass Walls, Mahogany Desk Surface",
  Lifestyle = "Urban Coffee Shop Table, Wood Texture, Sunlight through Window, Latte Art",
  Nature = "Organic Stone Surface, Moss Accents, Soft Diffused Natural Light",
  Gradient = "Abstract Mesh Gradient Background, Tech-Focused Colors, Smooth Transitions",
  Dark = "Matte Black Surface, Dark Mode Aesthetic, Cyberpunk LED Accents",
  Wood = "Rich Walnut Wood Desk Texture, Top-Down View, Office Essentials",
  Geometric = "3D Abstract Architectural Geometry, Glass Prisms, Clean Lines",
  City = "Bokeh City Skyline at Dusk, Out-of-focus Street Lights, Premium Atmosphere"
}

export enum LightingStyle {
  Auto = "✨ AI Auto-Enhance (Best Visibility)",
  Soft = "Softbox Studio Lighting, Even Illumination, Soft Shadows, High Visibility",
  Dramatic = "High Contrast Rim Lighting, Silhouette Effect, Moody Atmosphere",
  Neon = "Cyberpunk Neon Lighting (Pink/Cyan), Reflective Surfaces, Night Mode",
  Natural = "Golden Hour Sunlight casting Long Shadows, Warm Organic Glow",
  GoldenHour = "Direct Warm Sunset Light, Lens Flares, Rich Orange Tones",
  StudioBox = "Pure White Commercial Lightbox, No Shadows, Maximum Product Clarity"
}

export enum CameraAngle {
  Auto = "✨ AI Best Angle (Dynamic Composition)",
  Front = "Direct Frontal View (0 degrees), Perfectly Symmetrical, Flat Plane",
  Isometric = "Isometric Projection (30 degrees), Technical Diagram Style, Sharp Edges",
  TopDown = "90-Degree Top-Down Flatlay, Perfectly Aligned, No Perspective Distortion",
  Perspective = "Three-Quarter View (45 degrees), Dynamic Product Depth, Hero Shot",
  Floating = "Levitating Device, Parallel to Camera, Shadow Hovering Below"
}

export enum ContentFit {
  Cover = "Fill Screen (Crop to Fit)",
  Contain = "Fit Entire Image (Letterbox if needed)",
  TopAlign = "Top Align (For Long/Scrolling Apps)"
}

export interface MockupSettings {
  deviceType: DeviceType;
  backgroundStyle: BackgroundStyle;
  lighting: LightingStyle;
  angle: CameraAngle;
  colorMood: string;
  // New Image Placement Control
  contentFit: ContentFit;
  
  customPrompt?: string;
  marketingTagline?: string; // Tagline entered by user or generated by AI
  description?: string; // User provided description
  customBackgroundPrompt?: string; // Specific prompt for custom backgrounds
  
  // User overrides for refinement
  targetSeoTitle?: string;
  targetSocialCaption?: string;
  
  // Advanced Analysis Data (Optional, populated by Auto-Analyze)
  detectedAppCategory?: string;
  detectedAudience?: string;
  detectedColors?: string[];
  suggestedProps?: string[];

  // Features
  enableAbTesting?: boolean;
}

export interface GeneratedImage {
  id: string;
  url: string;
  prompt: string;
  timestamp: number;
  tagline?: string; // Tagline associated with this generation
  strategy?: string; // Short description of the visual strategy
  
  // SEO & Content Data
  seoTitle?: string;
  seoKeywords?: string;
  socialCaption?: string;
  altText?: string;
  isFavorite?: boolean;

  // Advanced Analysis Persistence
  conversionScore?: number; // 0-100
  appCategory?: string;
  targetAudience?: string;
  dominantColors?: string[]; // Hex codes
  suggestedProps?: string[];

  // Stored for restoration/filtering
  deviceType: string;
  backgroundStyle: string;
  lighting: string;
  angle: string;
  colorMood: string;
  customPrompt?: string;
  description?: string;
  contentFit?: ContentFit;
  customBackgroundPrompt?: string;
  
  // Source for refinement
  originalBase64?: string;
  originalMimeType?: string;
  
  // Variant Info
  variantLabel?: string; // "Variant A" or "Variant B"
}
